// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgG7qOeD0LG0ac6RvGXCEziGcghQFpRK0',
    appId: '1:111865592557:web:2903a4440e16085fa3eae4',
    messagingSenderId: '111865592557',
    projectId: 'assignment4-mobile',
    authDomain: 'assignment4-mobile.firebaseapp.com',
    storageBucket: 'assignment4-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2_2CLcKgJtkyxVNJlPh5sO9cz7LGueA',
    appId: '1:111865592557:android:1761c0aa16a731b0a3eae4',
    messagingSenderId: '111865592557',
    projectId: 'assignment4-mobile',
    storageBucket: 'assignment4-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg6p7a0FtT6ad9rtSivy_4SEJDRaWpXvc',
    appId: '1:111865592557:ios:3b11f979b344248ba3eae4',
    messagingSenderId: '111865592557',
    projectId: 'assignment4-mobile',
    storageBucket: 'assignment4-mobile.appspot.com',
    iosBundleId: 'com.example.assignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg6p7a0FtT6ad9rtSivy_4SEJDRaWpXvc',
    appId: '1:111865592557:ios:3b11f979b344248ba3eae4',
    messagingSenderId: '111865592557',
    projectId: 'assignment4-mobile',
    storageBucket: 'assignment4-mobile.appspot.com',
    iosBundleId: 'com.example.assignment3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgG7qOeD0LG0ac6RvGXCEziGcghQFpRK0',
    appId: '1:111865592557:web:075b53a7986ec234a3eae4',
    messagingSenderId: '111865592557',
    projectId: 'assignment4-mobile',
    authDomain: 'assignment4-mobile.firebaseapp.com',
    storageBucket: 'assignment4-mobile.appspot.com',
  );
}
